services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: projem-frontend

    ports:
      - "5173:5173"

    environment:
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"

    volumes:
      - ./app:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules: